#!/bin/bash

# athugar hvort .sql skrain se nyrri en gagnagrunnurinn og recompilar ef svo er
[ ../profSchema.sql -nt ./profSchema.db ] && $(echo '.save profSchema.db' | sqlite3 -init ../profSchema.sql) && echo 'Recompiled'

[ -z "$1" ] && echo "keyrsla: ./test <query.sql>" || sqlite3 profSchema.db ".read $1" 